### ISSUE TITLE
integration tests

### ISSUE THREAD

**Issue by tauli** [kiebitz-oss/vanellus#11]
Complete integration tests for user, provider and mediator which represent a typical end user workflow and illustrate how the api is intended to be used.

- [ ] user
- [ ] provider
- [ ] mediator

**Comment by adewes** [comment]
I don't think this is necessary, there are already tests for all lifecycle methods, I don't see what redundant tests add on top of that? Of course they don't hurt except for making changes a bit more cumbersome, but I don't see the advantage.

If you want to have examples of how to use the API I'd put those into the documentation rather than a test.
